class BeiraNeighborhoods {
  BeiraNeighborhoods._();

  static const List<String> list = [
    'Alto da Manga',
    'Alvalade',
    'Central',
    'Chaimite',
    'Chingussura',
    'Chipangara',
    'Chota',
    'Estoril',
    'Estorril',
    'Esturro',
    'Goto',
    'Inhamizua',
    'Macurungo',
    'Macurti',
    'Macuti',
    'Manga',
    'Manga Mascarenha',
    'Maraza',
    'Marraza',
    'Mascarenha',
    'Matacuane',
    'Matadouro',
    'Matope',
    'Muave',
    'Munassa',
    'Mungassa',
    'Munhava',
    'Ndunda',
    'Nhaconjo',
    'Nhangau',
    'Nhangoma',
    'Pioneiros',
    'Ponta Gea',
    'Ponta Gêa',
    'Tchondja',
    'Vaz',
    'Vaz Manga',
    'Vila Massane',
  ];
}
