name: Gerar APK Txeneza

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Criar ficheiro .env a partir de Secrets
        env:
          ENV_SECRET: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_SECRET" > .env

      - name: Instalar dependências
        run: flutter pub get

      - name: Compilar APK (Release)
        run: flutter build apk --release

      - name: Guardar Ficheiro APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: txeneza-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
